---
driver:
  name: ec2
  ssh_connection_options:
    - -o ControlPersist=30m

lint:
  name: yamllint
  options:
    config-file: .yamllint

platforms:
  - name: centos7-aws
    image: ${STIG_CI_CENTOS_AWS_AMI_ID:-default}
    instance_type: t2.medium
    vpc_subnet_id: ${STIG_CI_AWS_VPC_SUBNET_ID}
    ssh_user: centos
    region: ${STIG_CI_AWS_REGION}
    security_group_vpc: ${STIG_CI_AWS_VPC_ID}

  - name: rhel7-aws
    image: ${STIG_CI_RHEL_AWS_AMI_ID:-default}
    instance_type: t2.medium
    ssh_user: ec2-user
    vpc_subnet_id: ${STIG_CI_AWS_VPC_SUBNET_ID}
    region: ${STIG_CI_AWS_REGION}
    security_group_vpc: ${STIG_CI_AWS_VPC_ID}

provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible
      retry_files_enabled: false

scenario:
  name: aws
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    # - idempotence # Current bug with lineinfile module
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: false
